#+TITLE: BRYAN'S GNU Emacs Config
#+AUTHOR: Bryan Yep
#+DESCRIPTION: Bryan's personal Emacs config.
#+STARTUP: showeverything
#+OPTIONS: toc:2

* TABLE OF CONTENTS :toc:
- [[#lexical-binding][LEXICAL BINDING]]
- [[#compilation-rules-on-windows][COMPILATION RULES ON WINDOWS]]
- [[#important-programs-to-load-first][IMPORTANT PROGRAMS TO LOAD FIRST]]
  - [[#adding-the-scripts-directory-to-the-path][Adding the scripts directory to the path]]
  - [[#sourcing-the-scripts][Sourcing the scripts]]
- [[#all-the-icons][ALL THE ICONS]]
- [[#backup-files][BACKUP FILES]]
- [[#company][COMPANY]]
- [[#dashboard][DASHBOARD]]
- [[#diminish][DIMINISH]]
- [[#dired][DIRED]]
- [[#evil][EVIL]]
- [[#flycheck][FLYCHECK]]
- [[#fonts][FONTS]]
  - [[#setting-the-font-face][Setting the Font Face]]
  - [[#zooming-inout][Zooming In/Out]]
- [[#general-keybindings][GENERAL KEYBINDINGS]]
- [[#git-programs][GIT PROGRAMS]]
  - [[#git-time-machine][Git Time Machine]]
  - [[#magit][Magit]]
- [[#graphical-user-interface-tweaks][GRAPHICAL USER INTERFACE TWEAKS]]
  - [[#disable-menubar-toolbars-and-scrollbars][Disable Menubar, Toolbars and Scrollbars]]
  - [[#display-line-numbers-and-truncated-lines][Display Line Numbers and Truncated Lines]]
- [[#highlight-todo][HIGHLIGHT TODO]]
- [[#ivy-counsel][IVY (COUNSEL)]]
- [[#language-support][LANGUAGE SUPPORT]]
- [[#minibuffer-escape][MINIBUFFER ESCAPE]]
- [[#modeline][MODELINE]]
- [[#nerd-icons][NERD-ICONS]]
- [[#neotree][NEOTREE]]
- [[#org-mode][ORG MODE]]
  - [[#enable-table-of-contents][Enable Table of Contents]]
  - [[#enable-org-bullets][Enable Org Bullets]]
  - [[#enable-org-cycle-in-evil-normal-mode][Enable Org-Cycle In Evil Normal Mode]]
  - [[#enable-image-rendering-in-org-mode][Enable Image Rendering In Org Mode]]
  - [[#disable-electric-indent][Disable Electric Indent]]
  - [[#source-code-block-tag-expansion][Source Code Block Tag Expansion]]
- [[#perspective][PERSPECTIVE]]
- [[#projectile][PROJECTILE]]
- [[#rainbow-delimiters][RAINBOW DELIMITERS]]
- [[#rainbow-mode][RAINBOW MODE]]
- [[#scrolling-behaviour][SCROLLING BEHAVIOUR]]
- [[#shells-and-terminals][SHELLS AND TERMINALS]]
  - [[#eshell][Eshell]]
  - [[#vterm][Vterm]]
  - [[#vterm-toggle][Vterm-Toggle]]
  - [[#eat][Eat]]
- [[#sudo-edit][SUDO EDIT]]
- [[#theme][THEME]]
- [[#transparency][TRANSPARENCY]]
- [[#which-key][WHICH-KEY]]

* LEXICAL BINDING

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-

;; Emacs will soon enable lexical-binding by default. To avoid breaking retro-compatibility with Elisp files that require dynamic binding,
;; a cookie comment is required at the very top of every document indicating whether lexical-binding is enabled or not.
;; To enable lexical-binding, set the flag to t; to disable it and enable legacy dynamic-binding, set it to nil.
#+end_src

* COMPILATION RULES ON WINDOWS
Emacs needs special tools and directives to compile some of its packages on Windows.
This is not needed on POSIX systems (Linux/MacOS).

#+begin_src emacs-lisp
(when (eq system-type 'windows-nt) ; This block of code only executes conditionally if ran on a Windows system

  ;; Add compiler executables to Emacs internal PATH
  ;; Make sure to have MSYS2 installed and the following packages in it:
  ;; - mingw-w64-ucrt-x86_64-gcc
  ;; - git
  ;; - make
  ;; You can install all of these with the following command on the MSYS2 command line:
  ;; pacman -S mingw-w64-ucrt-x86_64-gcc git make
  ;; Make sure all the absolute paths match the actual locations of the tools' binaries
  (setenv "PATH" (concat "C:\\tools\\msys64\\ucrt64\\bin;C:\\tools\\msys64\\usr\\bin;" (getenv "PATH")))
  (setq exec-path (append '("C:/tools/msys64/ucrt64/bin" "C:/tools/msys64/usr/bin") exec-path))

  ;; Tell GCC where to look for the native compilation libraries
  (setenv "LIBRARY_PATH" "C:\\tools\\msys64\\ucrt64\\lib;C:\\tools\\msys64\\ucrt64\\lib\\gcc\\x86_64-w64-mingw32\\14.1.0") ; Adjust version number if necessary

  ;; Tell Emacs explicitely where is the GCC driver
  (setq native-comp-driver-path "C:/tools/msys64/ucrt64/bin/gcc.exe")
  
  ;; Suppress annoying alerts while compiling under the hood
  ;; (setq native-comp-async-report-warnings-errors 'silent)

  ;; SOLUTION FOR EVIL TRAMPOLINES ON WINDOWS
  ;; Disables compilation trampolines on Windows
  (setq native-comp-enable-subr-trampolines nil))
#+end_src

* IMPORTANT PROGRAMS TO LOAD FIRST

** Adding the scripts directory to the path

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src

** Sourcing the scripts

#+begin_src emacs-lisp
(require 'elpaca-setup)  ;; The Elpaca Package Manager
(require 'buffer-move)   ;; Buffer-move for a better window management
(require 'app-launchers) ;; Use Emacs as a run launcher like dmenu (experimental)
#+end_src

* ALL THE ICONS
This is an icon set that can be used with dashboard, dired, ibuffer and other Emacs programs.

#+begin_src emacs-lisp
(use-package all-the-icons :ensure t :demand t
  :if (display-graphic-p))

(use-package all-the-icons-dired :ensure t :demand t
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))
#+end_src

* BACKUP FILES
By default, Emacs creates automatic backups of files in their original directories, such as "file.el" and the backup "file.el~".
This leads that it creates a lot of clutter, so let's tell Emacs to put all backups that it creates in the =TRASH= directory.
On Windows systems, we will send the backups to a specialized directory: "~/.config/emacs/backups".

#+begin_src emacs-lisp
(when (eq system-type 'windows-nt) ; For Windows systems
  (setq backup-directory-alist '((".*" . "~/.config/emacs/backups"))))
(unless (eq system-type 'windows-nt) ; For POSIX systems
  (setq backup-directory-alist '((".*" . "~/.local/share/Trash/files"))))
#+end_src

* COMPANY
Company is a text completion framework for Emacs. The name stands for "complete anything".
Completion will start automatically after you type a few letters. use M-n and M-p to select,
<return> to complete or <tab> to complete the common part.

#+begin_src emacs-lisp
(use-package company
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  (global-company-mode t))

(use-package company-box
  :after company
  :diminish
  :hook (company-mode . company-box-mode))
#+end_src

* DASHBOARD
Emacs Dashboard is an extensible startup screen showing you recent files,
bookmarks, agenda items and an Emacs banner.

#+begin_src emacs-lisp
(use-package dashboard
  :ensure t
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
  (setq dashboard-startup-banner 'logo)
  ;; (setq dashboard-startup-banner "~/.config/emacs/images/emacs-dash.png") ;; use custom image as banner
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5)
                          (bookmarks . 3)
                          (projects . 3)
                          (registers . 3)))
  ;; (dashboard-modify-heading-icons '((recents . "file-text")
  ;;                             (bookmarks . "book")))
  :config
  (dashboard-setup-startup-hook))
#+end_src

* DIMINISH
This package implements hiding or abbreviation of the modeline displays (lighters) of
minor-modes. With this package installed, you can add ':diminish' to any use-package block
to hide that particular mode in the modeline.

#+begin_src emacs-lisp
(use-package diminish :ensure t)
#+end_src

* DIRED
#+begin_src emacs-lisp
(use-package dired-open :ensure t
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
				("jpg" . "sxiv")
				("png" . "sxiv")
				("mkv" . "mpv")
				("mp4" . "mpv"))))

(use-package peep-dired :ensure t
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)
#+end_src

* EVIL
Evil is an extensible vi/vim layer for Emacs. Because... let's face it. The Vim keybindings are just plain better.

#+begin_src emacs-lisp
(use-package evil :ensure t :demand t
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (setq evil-undo-system 'undo-redo) ;; Adds Vim-like C-r redo functionality
  (setq evil-want-C-u-scroll t) ;; Enables C-u to jump half a page up
  (evil-mode))

(use-package evil-collection :ensure t :demand t
  :after evil
  ;; Do not uncomment this unless you want to specify each and every mode
  ;; that evil-collection should work with. The following line is here
  ;; for documentation purposes in case you need it.

  ;; (setq evil-collection-mode-list '(dashboard dired ibuffer))
  (add-to-list 'evil-collection-mode-list 'help) ;; Evilify help mode
  (evil-collection init))

(use-package evil-tutor :ensure t :demand t)

;; Using RETURN to follow links in Org/Evil.
;; Unmap keys in 'evil-maps. If not done, (setq org-return-follow-link t) will not work.
(with-eval-after-load 'evil-maps
  (define-key evil-motion-state-map (kbd "SPC") nil)
  (define-key evil-motion-state-map (kbd "RET") nil)
  (define-key evil-motion-state-map (kbd "TAB") nil))

;; Setting RETURN key in org-mode to follow links.
(setq org-return-follows-link t)
#+end_src

* FLYCHECK
Install =luacheck= from your Linux distro's repositories for flycheck to work correctly with
lua files. Install =python-pylint= for flycheck to work with python files.
Haskell works with flycheck as long as =haskell-ghc= or =haskell-stack-ghc= is installed.
For more information on language support for flycheck, read this.

#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :defer t
  :diminish
  :init (global-flycheck-mode))
#+end_src

* FONTS
Defining the various fonts that Emacs will use.

** Setting the Font Face
#+begin_src emacs-lisp
  (set-face-attribute 'default nil
   :font "JetBrains Mono"
   :height 110
   :weight 'medium)
  (set-face-attribute 'variable-pitch nil
   :font "Ubuntu"
   :height 120
   :weight 'medium)
  (set-face-attribute 'fixed-pitch nil
   :font "JetBrains Mono"
   :height 110
   :weight 'medium)
  ;; Makes commented text and keywords italic.
  ;; This is working in emacsclient but not emacs.
  ;; Your font must have an italic face available.
  (set-face-attribute 'font-lock-comment-face nil
   :slant 'italic)
  (set-face-attribute 'font-lock-keyword-face nil
   :slant 'italic)

  ;; This sets the default font on all graphical frames created after restarting Emacs.
  ;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
  ;; are not right unless I also add this method of the default font.
  (add-to-list 'default-frame-alist '(font . "JetBrains Mono-12"))

  ;; Uncomment the following line if line spacing needs adjusting.
  (setq-default line-spacing 0.12)
#+end_src

** Zooming In/Out
You can use the bindings CTRL plus +/- for zooming in/out.
You can also use the CTRL plus the mouse wheel for zooming in/out.

#+begin_src emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
#+end_src


* GENERAL KEYBINDINGS

#+begin_src emacs-lisp
(use-package general :ensure t :demand t
  :config
  (general-evil-setup)

  ;; set up  'SPC' as the global leader key
  (general-create-definer bryan/leader-keys
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC" ;; set leader key
    :global-prefix "M-SPC") ;; access leader in insert mode

  (bryan/leader-keys
   "SPC" '(counsel-M-x :wk "Counsel M-x")
   "." '(find-file :wk "Switch buffer")
   "f c" '((lambda () (interactive) (find-file "~/.config/emacs/config.org")) :wk "Edit Emacs config")
   "f r" '(counsel-recentf :wk "Find recent files")
   "TAB TAB" '(comment-line :wk "Comment lines"))

  (bryan/leader-keys
   "b" '(:ignore t :wk "Buffers")
   "b c" '(clone-indirect-buffer :wk "Clone indirect copy in a split")
   "b C" '(clone-indirect-buffer-other-window :wk "Clone indirect copy in a new window")
   "b b" '(switch-to-buffer :wk "Switch buffer")
   "b i" '(ibuffer :wk "Ibuffer")
   "b k" '(kill-this-buffer :wk "Kill this buffer")
   "b K" '(kill-some-buffers :wk "Kill multiple buffers")
   "b n" '(next-buffer :wk "Next buffer")
   "b p" '(previous-buffer :wk "Previous buffer")
   "b r" '(revert-buffer :wk "Reload buffer")
   "b R" '(rename-buffer :wk "Rename buffer")
   "b s" '(basic-save-buffer :wk "Save buffer")
   "b S" '(save-some-buffers :wk "Save multiple buffers"))

  (bryan/leader-keys
   "B" '(:ignore t :wk "Bookmarks")
   "B d" '(bookmark-delete :wk "Delete bookmark")
   "B l" '(list-bookmarks :wk "List bookmarks")
   "B m" '(bookmark-set :wk "Set bookmark")
   "B w" '(bookmark-save :wk "Save current bookmarks to bookmark file"))

  (bryan/leader-keys
   "d" '(:ignore t :wk "Dired")
   "d d" '(dired :wk "Open dired")
   "d j" '(dired-jump :wk "Dired jump to current")
   "d n" '(neotree-dir :wk "Open directory in neotree")
   "d p" '(peep-dired :wk "Peep-dired"))

  (bryan/leader-keys
   "e" '(:ignore t :wk "Evaluate/Eshell")
   "e b" '(eval-buffer :wk "Evaulate elisp in buffer")
   "e d" '(eval-defun :wk "Evaluate defun containing or after point")
   "e e" '(eval-expression :wk "Evaluate an elisp expression")
   "e l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
   "e r" '(evaluate-region :wk "Evaluate elisp in region")
   "e s" '(eshell :wk "Eshell")
   "e h" '(counsel-esh-history :wk "Eshell history"))

  (bryan/leader-keys
   "h" '(:ignore t :wk "Help")
   "h a" '(counsel-apropos :wk "Apropos")
   "h b" '(describe-bindings :wk "Describe bindings")
   "h c" '(describe-char :wk "Describe character under cursor")
   "h d" '(:ignore t :wk "Emacs documentation")
   "h d a" '(about-emacs :wk "About Emacs")
   "h d d" '(view-emacs-debugging :wk "View Emacs debugging")
   "h d f" '(view-emacs-FAQ :wk "View Emacs FAQ")
   "h d m" '(info-emacs-manual :wk "The Emacs manual")
   "h d n" '(view-emacs-news :wk "View Emacs news")
   "h d o" '(describe-distribution :wk "How to obtain Emacs")
   "h d p" '(view-emacs-problems :wk "View Emacs problems")
   "h d t" '(view-emacs-todo :wk "View Emacs todo")
   "h d w" '(describe-no-warranty :wk "Describe no warranty")
   "h e" '(view-echo-area-messages :wk "View echo area messages")
   "h f" '(describe-function :wk "Describe function")
   "h F" '(describe-face :wk "Describe face")
   "h g" '(describe-gnu-project :wk "Describe GNU project")
   "h i" '(info :wk "Info")
   "h I" '(describe-input-method :wk "Describe input method")
   "h k" '(describe-key :wk "Describe key")
   "h l" '(view-lossage :wk "Display recent keystrokes and the commands run")
   "h L" '(describe-language-environment :wk "Describe language environment")
   "h m" '(describe-mode :wk "Describe mode")
   "h r r" '((lambda () (interactive) (load-file "~/.config/emacs/init.el")) :wk "Reload Emacs config")
   "h t" '(load-theme :wk "Load theme")
   "h v" '(describe-variable :wk "Describe variable"))

  (bryan/leader-keys
   "m" '(:ignore t :wk "Org")
   "m a" '(org-agenda :wk "Org agenda")
   "m e" '(org-export-dispatch :wk "Org export dispatch")
   "m i" '(org-toggle-item :wk "Org toggle item")
   "m t" '(org-todo :wk "Org todo")
   "m B" '(org-babel-tangle :wk "Org babel tangle")
   "m T" '(org-todo-list :wk "Org todo list"))

  (bryan/leader-keys
   "m b" '(:ignore t :wk "Tables")
   "m b -" '(org-table-insert-hline :wk "Insert hline in table"))

  (bryan/leader-keys
   "m d" '(:ignore t :wk "Date/deadline")
   "m d t" '(org-time-stamp :wk "Org time stamp"))

  (bryan/leader-keys
   "t" '(:ignore t :wk "Toggle")
   "t l" '(display-line-numbers-mode :wk "Toggle line numbers")
   "t t" '(visual-line-mode :wk "Toggle truncated lines")
   "t v" '(vterm-toggle :wk "Toggle vterm"))

  (bryan/leader-keys
   "w" '(:ignore t :wk "Windows")
   ;; Window splits
   "w c" '(evil-window-delete :wk "Close window")
   "w n" '(evil-window-new :wk "New window")
   "w s" '(evil-window-split :wk "Horizontal split window")
   "w v" '(evil-window-vsplit :wk "Vertical split window")
   ;; Window motions
   "w h" '(evil-window-left :wk "Window left")
   "w j" '(evil-window-down :wk "Window down")
   "w k" '(evil-window-up :wk "Window up")
   "w l" '(evil-window-right :wk "Window right")
   "w w" '(evil-window-next :wk "Go to next window")
   ;; Move windows
   "w H" '(buf-move-left :wk "Buffer move left")
   "w J" '(buf-move-down :wk "Buffer move down")
   "w K" '(buf-move-up :wk "Buffer move up")
   "w L" '(buf-move-right :wk "Buffer move right"))
  )
#+end_src

* GIT PROGRAMS

** Git Time Machine
git-timemachine is a program that allows you to move backwards and forwards through a file's commits.
'SPC g t' will open the time machine on a file if it is on a git repo.
The, while in normal mode, you can use 'CTRL-j' and 'CTRL-k' to move backwards and forwards through the commits.

#+begin_src emacs-lisp
(use-package git-timemachine :ensure t
  :after git-timemachine
  :hook (evil-normalize-keymaps . git-timemachine-hook)
  :config
    (evil-define-key 'normal git-timemachine-mode-map (kbd "C-j") 'git-timemachine-show-previous-revision)
    (evil-define-key 'normal git-timemachine-mode-map (kbd "C-k") 'git-timemachine-show-next-revision)
)
#+end_src

** Magit
Magit is a full-featured git client for Emacs.

#+begin_src emacs-lisp
;; Magit requires Transient 0.13
;; Update Transient before installing Magit
(use-package transient
  :elpaca (transient :branch "main")
  :demand t)

(use-package magit :ensure t
  :after transient)
#+end_src

* GRAPHICAL USER INTERFACE TWEAKS
Let's make GNU Emacs look a little better.

** Disable Menubar, Toolbars and Scrollbars
#+begin_src emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
#+end_src

** Display Line Numbers and Truncated Lines
#+begin_src emacs-lisp
(global-display-line-numbers-mode 1)
(global-visual-line-mode t)
#+end_src

* HIGHLIGHT TODO
Adding highlights to TODO and related words.

#+begin_src emacs-lisp
(use-package hl-todo :ensure t
  :hook ((org-mode . hl-todo-mode)
	 (prog-mode . hl-todo-mode))
:config
(setq hl-todo-highlight-punctuation ":"
      hl-todo-keyword-faces
      `(("TODO"       warning bold)
	("FIXME"      error bold)
	("HACK"       font-lock-constant-face bold)
	("REVIEW"     font-lock-keyword-face bold)
	("NOTE"       success bold)
	("DEPRECATED" font-lock-doc-face bold))))
#+end_src

* IVY (COUNSEL)
+ Ivy, a generic completion mechanism for Emacs.
+ Counsel, a collection of Ivy-enhanced versions of common Emacs commands.
+ Ivy-rich allows us to add descriptions alongside the commands in M-x.
  
#+begin_src emacs-lisp
(use-package counsel :ensure t :demand t
  :after ivy
  :diminish
  :config (counsel-mode))

(use-package ivy
  :bind
  ;; ivy-resume resumes the last Ivy-based completion.
  (("C-c C-r" . ivy-resume)
   ("C-x B" . ivy-switch-buffer-other-window))
  :custom
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  (setq enable-recursive-minibuffers t)
  :diminish
  :config
  (ivy-mode))

(use-package all-the-icons-ivy-rich :ensure t :demand t
  :init (all-the-icons-ivy-rich-mode 1))

(use-package ivy-rich
  :after ivy
  :ensure t
  :init (ivy-rich-mode 1) ;; this gets us descriptions in M-x.
  :custom
  (ivy-virtual-abbreviate 'full
   ivy-rich-switch-buffer-align-virtual-buffer t
   ivy-rich-path-style 'abbrev)
  :config
  (ivy-set-display-transformer 'ivy-switch-buffer
                               'ivy-rich-switch-buffer-transformer))
#+end_src

* LANGUAGE SUPPORT
Emacs has built-in programming language modes for Lisp, Scheme, DSSSL, Ada, ASM, AWK C, C++,
Fortran, Icon, IDL (CORBA), IDLWAVE, Java, JavaScript, M4, Makefiles, Metafont, Modula2,
Object Pascal, Objective-C, Octave, Pascal, Perl, Pike, PostScript, Prolog, Python, Ruby,
Simula, SQL, Tcl, Verilog, and VHDL. Other languages will require you to install additional modes.

#+begin_src emacs-lisp
(use-package haskell-mode :ensure t)
(use-package php-mode :ensure t)
;; Search for the names of the packages for the languages that you need
#+end_src

* MINIBUFFER ESCAPE
By default, Emacs requires you to hit ESC three times to escape quit the minibuffer.
Let's fix that by changing it to one single ESC.

#+begin_src emacs-lisp
(global-set-key [escape] 'keyboard-escape-quit)
#+end_src

* MODELINE
The modeline is the bottom status bar that appears in the Emacs window.
While you can create your own custom modeline, why go through the problem
when Doom Emacs already has a nice modeline package available.
For more information on what is available to configure in the Doom modeline, check out: Doom Modeline

#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config
  (setq doom-modeline-height 25      ;; sets modeline height
	doom-modeline-bar-width 5    ;; sets right bar width
	doom-modeline-persp-name t   ;; adds perspective name to modeline
	doom-modeline-persp-icon t)) ;; adds folder icon next to persp name
#+end_src

* NERD-ICONS
You need *nerd-fonts* installed on the operating system for *nerd-icons* to work on Emacs.
If you are on a Windows system, you will need *Symbols Nerd Font* instead.

#+begin_src emacs-lisp
(use-package nerd-icons
  :ensure (:type git :host github :repo "rainstormstudio/nerd-icons.el")
  :config
  (if (or (member "Symbols Nerd Font" (font-family-list))
	  (member "SymbolsNerdFont" (font-family-list))
	  (member "JetBrainsMono Nerd Font" (font-family-list)))
      (require 'nerd-icons)
    (message "Warning: 'Symbols Nerd Font' not found on the system. nerd-icons will not work.")))
#+end_src

* NEOTREE
Neotree is a file tree viewer. When you open neotree, it jumps to the current file thanks to neo-smart-open.
The neo-window-fixed-size setting makes the neotree width be adjustable. Neotree provides the following themes:
classic, ascii, arrow, icons, and nerd. Theme can be configured by setting "two" themes for neo-theme:
one for the GUI and the other one for the terminal.
I like to use 'SPC t' for 'toggle' keybindings, so I have used 'SPC t n' for toggle-neotree.

| COMMAND        | DESCRIPTION                 | KEYBINDING |
|----------------+-----------------------------+------------|
| neotree-toggle | /Toggle neotree             | SPC t n    |
| neotree-dir    | /Open directory in neotree/ | SPC d n    |

#+begin_src emacs-lisp
(use-package neotree :ensure t
  :config
  (setq neo-smart-open t
	neo-show-hidden-files t
	neo-window-width 55
	neo-window-fixed-size nil
	inhibit-compacting-font-caches t
	projectile-switch-project-action 'neotree-projectile-action)
	;; truncate long file names in neotree
	(add-hook 'neo-after-create-hook
	  #'(lambda (_)
	      (with-current-buffer (get-buffer neo-buffer-name)
		(setq truncatelines t)
		(setq word-wrap nil)
		(make-local-variable 'auto-hscroll-mode)
		(setq auto-hscroll-mode nil)))))
#+end_src


* ORG MODE
** Enable Table of Contents

#+begin_src emacs-lisp
(use-package toc-org :ensure t :demand t
  :commands toc-org-enable
  :init (add-hook 'org-mode-hook 'toc-org-enable))
;; Ensure heading is always at the center of the screen when jumping from table of contents
(with-eval-after-load 'org
  (add-hook 'org-follow-link-hook #'recenter-top-bottom))
#+end_src

** Enable Org Bullets
Org-bullets gives us attractive bullets rather than asterisks.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  (use-package org-bullets :ensure t :demand t)
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

** Enable Org-Cycle In Evil Normal Mode
Org mode headings don't expand/collapse with TAB if you're on Evil mode normal mode.
This configuration enables it.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (with-eval-after-load 'evil-maps
    ;; Bind TAB in Evil Normal Mode to cycle headings
    (evil-define-key 'normal org-mode-map (kbd "<tab>") #'org-cycle)
    ;; Bind Shift-TAB in Evil Normal Mode to cycle global visibility
    (evil-define-key 'normal org-mode-map (kbd "<backtab>") #'org-global-cycle)))
#+end_src

** Enable Image Rendering In Org Mode

#+begin_src emacs-lisp
(setq org-startup-with-inline-images t)
#+end_src

** Disable Electric Indent
Org mode source blocks have some really weird and annoying default indentation behaviour.
I think this has to do with electric-indent-mode, which is turned on by default in Emacs.
So let's turn it OFF!

#+begin_src emacs-lisp
(electric-indent-mode -1)
(setq org-edit-src-content-indentation 0)
#+end_src

** Source Code Block Tag Expansion
Org-tempo is not a separate package but a module within org that can be enabled.
Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.
Other expansions available include:

| Typing the below + TAB | Expands to ...                            |
| <a                     | '#+BEGIN_EXPORT ascii' ... '#+END_EXPORT' |
| <c                     | '#+BEGIN_CENTER' ... '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' ... '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' ... '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' ... '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' ... '#+END_CENTER'  |
| <l                     | '#+BEGIN_EXPORT latex' ... '#+END_CENTER' |
| <q                     | '#+BEGIN_QUOTE' ... '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' ... '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' ... '#+END_VERSE'         |

#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src

* PERSPECTIVE
Perspective provides multiple named workspaces (or "perspectives") in Emacs, similar to multiple desktops in window managers.
Each perspective has its own buffer list and its own window layout, along with some other isolated niceties, like the xref ring.

#+begin_src emacs-lisp
(use-package perspective :ensure t
  :custom
  ;; NOTE! I have also set 'SPC =' to open the perspective menu.
  ;; I'm only setting the additional binding because setting it
  ;; helps suppress an annoying warning message.
  (persp-mode-prefix-key (kbd "C-c M-p"))
  :init
  (persp-mode)
  :config
  ;; Sets a file to write to when we save states.
  (setq persp-state-default-file "~/.config/emacs/sessions"))

;; This will group buffers by persp-name in ibuffer.
(add-hook 'ibuffer-hook
	  (lambda ()
	    (persp-ibuffer-set-filter-groups)
	    (unless (eq ibuffer-sorting-mode 'alphabetic)
	      (ibuffer-do-sort-by-alphabetic))))

;; Automatically save perspective states to file when Emacs exits.
(add-hook 'kill-emacs-hook #'persp-state-save)
#+end_src

* PROJECTILE
Projectile is a project interaction library for Emacs. It should be noted that many
projectile commands do not work if you have set "fish" as the "shell-file-name" for Emacs.

#+begin_src emacs-lisp
(use-package projectile :ensure t
  :diminish
  :config
  (projectile-mode 1))
#+end_src

* RAINBOW DELIMITERS
Adding rainbow coloring to parentheses () and other symbols such as brackets [] and braces {}.

#+begin_src emacs-lisp
(use-package rainbow-delimiters :ensure t
  :hook ((emacs-lisp-mode . rainbow-delimiters-mode)
	 (clojure-mode . rainbow-delimiters-mode)))
#+end_src

* RAINBOW MODE
Display the actual color as a background for any hex color value (ex. #ffffff).
The code block below enables rainbow-mode in all programming modes (prog-mode)
as well as org-mode, which is why rainbow works on this document.

#+begin_src emacs-lisp
(use-package rainbow-mode :ensure t :demand t
  :hook org-mode prog-mode)
#+end_src

* SCROLLING BEHAVIOUR
Emacs scrooling behaviour by default is clumsy. This helps make it more natural and smooth.

#+begin_src emacs-lisp
;; Force pixel-perfect calculations to handle fractional spacing
(setq-default window-resize-pixelwise t)
(setq-default frame-resize-pixelwise t)
;; Enable modern pixel-precise scrolling behaviour
(pixel-scroll-precision-mode 1)
;; Force keyboard line commands to scroll cleanly by pixel-line heights
(setq pixel-scroll-precision-large-scroll-height 1)
;; Force keyboard scrolling to move an exact number of lines at a time when the cursor moves off-screen
(setq scroll-step 1)
;; Setting this to a value greater than 100 tells Emacs to never center the screen automatically
(setq scroll-conservatively 100000)
;; Disabling this prevents Emacs from automatically adjusting vertical scrolling for tall lines or varied fonts
(setq auto-window-vscroll nil)
;; Setting this to 0 means scrolling triggers only when the cursor touches the absolute bottom or top of the edge
(setq scroll-margin 0)
;; Force line-move to respect the absolute pixel height of lines
(setq line-move-visual t)
#+end_src

* SHELLS AND TERMINALS

** Eshell
Eshell is an Emacs 'shell' that is written in Elisp.

#+begin_src emacs-lisp
(use-package eshell-syntax-highlighting :ensure t :demand t
  :after esh-mode
  :config
  (eshell-syntax-hightlighting-global-mode +1))

;; eshell-syntax-highlighting -- adds fish/zsh-like syntax highlighting.
;; eshell-rc-script -- your profile for eshell; like a bashrc for eshell.
;; eshell-aliases-file -- sets an aliases file for eshell.

(setq eshell-rc-script (concat
user-emacs-directory "eshell/profile")
      eshell-aliases-file (concat
      user-emacs-directory "eshell/aliases")
      eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
      shell-visual-commands '(
        "bash"
        "fish"
        "htop"
        "ssh"
        "top"
        "zsh"
      ))
#+end_src

** Vterm
Vterm is a terminal emulator within Emacs. The 'shell-file-name' setting sets the shell
to be used in M-x shell, M-x term, M-x ansi-term and M-x vterm.
By default, the shell is set to 'fish' but could change it to 'bash' or 'zsh' if you prefer.

#+begin_src emacs-lisp
(use-package vterm :ensure t :demand t
:if (not (eq system-type 'windows-nt)) ; Avoids installing Vterm if running Emacs on a Windows system
;; Vterm is not compatible with Windows, because it requires termios.h for compilation,
;; a C library that is exclusive of POSIX systems (Linux and MacOS)
:config
(setq shell-file-name "/bin/zsh"
      vterm-max-scrollback 5000))
#+end_src

** Vterm-Toggle
vterm-toggle toggles between the vterm buffer and whatever buffer you are editing.

#+begin_src emacs-lisp
(use-package vterm-toggle :ensure t
  :after vterm
  :config
  (setq vterm-toggle-fullscreen-p nil)
  (setq vterm-toggle-scope 'project)
  (add-to-list 'display-buffer-alist
               '((lambda (buffer-or-name _)
                     (let ((buffer (get-buffer buffer-or-name)))
                       (with-current-buffer buffer
                         (or (equal major-mode 'vterm-mode)
                             (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                  (display-buffer-reuse-window display-buffer-at-bottom)
                  ;; (display-buffer-reuse-window display-buffer-in-direction)
                  ;; display-buffer-in-direction/direction/dedicated is added in Emacs 27
                  ;; (direction . bottom)
                  ;; (dedicated . t) ; dedicated is supported in Emacs 27
                  (reusable-frames . visible)
                  (window-height . 0.3))))
#+end_src

** Eat
Eat is a terminal emulator within Emacs, which is more friendly with Windows systems.
We will only install this package if we are on a Windows system.

#+begin_src emacs-lisp
(when (eq system-type 'windows-nt) ; Only install on Windows systems
  (use-package eat
    :ensure (:host codeberg :repo "akib/emacs-eat"
	     :files ("*.el" ("term" "term/*.el") "*.texi" "*.ti"))
    :config
  (setq explicit-shell-file-name "cmdproxy.exe")
  (add-hook 'eshell-load-hook #'eat-eshell-mode)
  (add-hook 'eshell-load-hook #'eat-eshell-visual-command-mode)))
#+end_src

* SUDO EDIT
sudo-edit gives us the ability to open files with sudo privileges
or switch over to editing with sudo privileges if we initially
opened the file without such privileges.

#+begin_src emacs-lisp
(use-package sudo-edit :ensure t :demand t
  :config
    (bryan/leader-keys
      "f u" '(sudo-edit-find-file :wk "Sudo find file")
      "f U" '(sudo-edit :wk "Sudo edit file")))
#+end_src

* THEME
The first of the two lines below designates the directory where we will place all of out themes.
The second line loads our chosen theme. As an example, we will use *munich-black*, a theme created
with the help of the [[https://mswift42.github.io/themecreator/][Emacs Theme Editor]].

#+begin_src emacs-lisp
(add-to-list 'custom-theme-load-path "~/.config/emacs/themes/")
(use-package doom-themes :ensure t
  :config
  (setq doom-themes-enable-bold- t ; if nil, bold is universally disabled
	doom-themes-enable-italic t) ; if nil, italics is universally disabled
;; Set the default theme to load
(load-theme 'munich-black t)
;; Enable custom neotree theme (all-the-icons must be installed)
(doom-themes-neotree-config)
;; Corrects (and improves) org-mode's native fortification
(doom-themes-org-config))
#+end_src

* TRANSPARENCY
With Emacs versions >=29, true transparency has been added.

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background . 90)) ; For all new frames henceforth
#+end_src

* WHICH-KEY
#+begin_src emacs-lisp
(use-package which-key
  :init
  (which-key-mode 1)
  :config
  (setq which-key-side-window-location 'bottom
	which-key-sort-order #'which-key-key-order-alpha
	which-key-sort-uppercase-first nil
	which-key-add-column-padding 1
	which-key-max-display-columns nil
	which-key-min-display-lines 6
	which-key-side-window-slot -10
	which-key-side-window-max-height 0.25
	which-key-idle-delay 0.8
	which-key-max-description-length 25
	which-key-allow-imprecise-window-fit nil
	which-key-separator " ➔ "))
#+end_src
